name: Edge Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "10 4 * * */2"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: gemfiles/view_component_master.gemfile
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.2"]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Ruby Next
      run: bundle exec rake nextify
    - name: Run tests
      run: |
        bundle exec rake test:isolated
